require 'rake/testtask'
Rake::TestTask.new do |t|
  t.libs << "test"
  t.test_files = FileList['test/**/*_test.rb']
  t.verbose = true
end

desc 'Compiles kernel files'
task :kernel do
  Dir['kernel/*.rb'].each do |src|
    dest = "../#{src.gsub('rb','tvm')}"
    puts "Compiling #{src} to #{dest}..."
    `bin/terror #{src} > #{dest}`
  end
end

desc 'Compiles example files'
task :examples do
  Dir['examples/*.rb'].each do |src|
    dest = "../#{src.gsub('rb','tvm')}"
    puts "Compiling #{src} to #{dest}..."
    `bin/terror #{src} > #{dest}`
  end
end

desc 'Compiles standard library'
task :stdlib do
  Dir['stdlib/*.rb'].each do |src|
    dest = "../#{src.gsub('rb','tvm').gsub('std','')}"
    puts "Compiling #{src} to #{dest}..."
    `bin/terror #{src} > #{dest}`
  end
end

task :default => :test
